// Short supplementary examples; these are not additional textbook passages.
window.WORD_EXAMPLES = [
  ['friendly classmate','My new classmate is friendly.','我的新同学很友好。'],
  ['greet greeting','We greet our teacher every morning.','我们每天早晨向老师问好。'],
  ['introduce myself','Let me introduce myself.','让我介绍一下自己。'],
  ['introduction self-introduction','This is my self-introduction.','这是我的自我介绍。'],
  ['grade middle','I am in Grade 7 at a middle school.','我在一所中学读七年级。'],
  ['glad meet','I am glad to meet you.','我很高兴见到你。'],
  ['same','We are in the same class.','我们在同一个班。'],
  ['hobby','My hobby is reading.','我的爱好是阅读。'],
  ['piano play','I can play the piano.','我会弹钢琴。'],
  ['love','I love my school.','我爱我的学校。'],
  ['like','I like music.','我喜欢音乐。'],
  ['always ready help','I am always ready to help you.','我总是乐意帮助你。'],
  ['full energy','Simon is full of energy.','西蒙精力充沛。'],
  ['sport healthy','Sport keeps me healthy.','运动使我保持健康。'],
  ['often football after','I often play football after school.','我经常放学后踢足球。'],
  ['slim','Sandy is tall and slim.','桑迪又高又苗条。'],
  ['hair','She has long hair.','她留着长发。'],
  ['polite','He is a polite boy.','他是一个有礼貌的男孩。'],
  ['music','I like listening to music.','我喜欢听音乐。'],
  ['well','She can swim very well.','她游泳游得很好。'],
  ['wear glasses','I wear glasses.','我戴眼镜。'],
  ['smart','Daniel is a smart boy.','丹尼尔是一个聪明的男孩。'],
  ['interested science','I am interested in science.','我对科学感兴趣。'],
  ['helpful','My friend is very helpful.','我的朋友很乐于助人。'],
  ['learn','We learn English at school.','我们在学校学习英语。'],
  ['pretty','She has a pretty bag.','她有一个漂亮的包。'],
  ['lovely','You have lovely eyes.','你的眼睛很漂亮。'],
  ['shy quiet','Kitty is shy and quiet.','基蒂害羞又安静。'],
  ['dance','I like to dance.','我喜欢跳舞。'],
  ['cute','The cat is small and cute.','这只猫小巧又可爱。'],
  ['swim','I can swim.','我会游泳。'],
  ['stay','Stay happy every day.','每天都要保持快乐。'],
  ['match','We have a football match today.','我们今天有一场足球比赛。'],
  ['luck','Good luck with your test!','祝你考试顺利！'],
  ['favourite subject','My favourite subject is English.','我最喜欢的学科是英语。'],
  ['interesting','This book is interesting.','这本书很有趣。'],
  ['problem','This Maths problem is easy.','这道数学题很简单。'],
  ['enjoy','I enjoy reading with my friends.','我喜欢和朋友们一起阅读。'],
  ['chess weekend','I play chess at the weekend.','我周末下棋。'],
  ['ping-pong','I like playing ping-pong.','我喜欢打乒乓球。'],
  ['fun','Our English class is fun.','我们的英语课很有趣。'],
  ['nickname','My nickname is Tom.','我的昵称是汤姆。'],
  ['popular','Football is popular at our school.','足球在我们学校很受欢迎。'],
  ['parent','Each parent gets a letter.','每位家长都会收到一封信。'],
  ['informal','Hi is an informal greeting.','Hi 是一种非正式的问候语。'],
  ['yourself','Tell me about yourself.','跟我说说你自己吧。'],
  ['herself','She introduces herself to the class.','她向全班同学介绍自己。'],
  ['ourself','We introduce ourselves to our new teacher.','我们向新老师介绍自己。'],
  ['start starts story','Our story starts today.','我们的故事今天开始。'],
  ['first day','Today is my first day at school.','今天是我上学的第一天。'],
  ['want','I want to make new friends.','我想结交新朋友。'],
  ['someone','Someone is at the door.','有人在门口。'],
  ['lot','I like this school a lot.','我非常喜欢这所学校。'],
  ['clean','Our classroom is clean.','我们的教室很干净。'],
  ['easy','This question is easy.','这个问题很简单。'],
  ['hard','This question is hard for me.','这个问题对我来说很难。'],
  ['right','Your answer is right.','你的答案是对的。'],
  ['bye','Bye! See you tomorrow.','再见！明天见。'],
  ['say','Please say your name.','请说出你的名字。'],
  ['name','My name is Amy.','我的名字是埃米。'],
  ['age','We are the same age.','我们同龄。'],
  ['late','I am not late for school.','我上学没有迟到。'],
  ['fine','I am fine, thank you.','我很好，谢谢你。'],
  ['time','It is time for school.','该上学了。'],
  ['kite','My kite is red.','我的风筝是红色的。'],
  ['use','I use a pen to write.','我用钢笔写字。'],
  ['make','Let us make a kite.','让我们做一个风筝吧。'],
  ['place','School is a great place to learn.','学校是一个学习的好地方。'],
  ['gate','Meet me at the school gate.','在学校门口和我见面吧。'],
  ['page','Please read this page.','请读这一页。'],
  ['race','We have a race today.','我们今天有一场赛跑。'],
  ['hide','I hide my toy under the bed.','我把玩具藏在床下。'],
  ['rise','I rise early every morning.','我每天早晨起得很早。'],
  ['life','I like my school life.','我喜欢我的学校生活。'],
  ['size','What size is your schoolbag?','你的书包是多大尺寸的？'],
  ['hope','I hope you like this book.','我希望你喜欢这本书。'],
  ['joke','Let me tell you a joke.','让我给你讲个笑话。'],
  ['note notes','I write a note to my friend.','我给朋友写了一张便条。'],
  ['rose','This rose is red.','这朵玫瑰是红色的。'],
  ['character','She has a quiet character.','她的性格很安静。'],
  ['sentence word','Read the words in this sentence.','读一读这个句子里的单词。'],
  ['sound','I like the sound of the piano.','我喜欢钢琴的声音。'],
  ['letter','A is the first letter.','A 是第一个字母。'],
  ['vowels','The letters a, e, i, o and u are vowels.','字母 a、e、i、o 和 u 是元音字母。'],
  ['verb','Play is a verb.','Play 是一个动词。'],
  ['simple','This is a simple question.','这是一个简单的问题。'],
  ['present tense','We use the present tense here.','我们在这里用现在时。'],
  ['facts','This book has facts about science.','这本书介绍了一些科学事实。'],
  ['states','Happy and sad are different states.','高兴和悲伤是不同的状态。'],
  ['positive negative','I am happy is positive; I am not happy is negative.','I am happy 是肯定句；I am not happy 是否定句。'],
  ['question','May I ask a question?','我可以问一个问题吗？'],
  ['correct','Your answer is correct.','你的答案是正确的。'],
  ['forms','Am, is and are are forms of be.','Am、is 和 are 都是 be 的形式。'],
  ['complete','Please complete this sentence.','请补全这个句子。'],
  ['conversation','We have a conversation in English.','我们用英语进行了一段对话。'],
  ['partner','My partner is Daniel.','我的搭档是丹尼尔。'],
  ['pairs work','We work in pairs.','我们两人一组学习。'],
  ['below box','Write your name in the box below.','把你的名字写在下面的方框里。'],
  ['different','We have different hobbies.','我们有不同的爱好。'],
  ['share','I share my books with Amy.','我和埃米分享我的书。'],
  ['true','It is true that I love reading.','我确实很喜欢阅读。'],
  ['false','This answer is false.','这个答案是错误的。'],
  ['information','Write your information here.','在这里写下你的信息。'],
  ['website','Our school has a website.','我们学校有一个网站。'],
  ['post photo','I post a photo on the school website.','我在学校网站上发布了一张照片。'],
  ['model','Use this sentence as a model.','以这个句子作为范例。'],
  ['comma pause','Pause at the comma.','在逗号处停顿。'],
  ['separate','Keep your books separate from mine.','把你的书和我的书分开放。'],
  ['stop','Please stop at the school gate.','请在学校门口停下。'],
  ['end','Put a full stop at the end.','在结尾加上句号。'],
  ['mark','Put a question mark here.','在这里加上问号。'],
  ['describe','Can you describe your new friend?','你能描述一下你的新朋友吗？'],
  ['pronounce correctly','I can pronounce this word correctly.','我能正确地读出这个单词。'],
  ['spend','I spend time reading every day.','我每天花时间阅读。'],
  ['action plan','This is my action plan.','这是我的行动计划。'],
  ['further study','I want to study English further.','我想进一步学习英语。'],
  ['order','Write the names in this order.','按照这个顺序写名字。'],
  ['message send','I send a message to my friend.','我给朋友发了一条消息。'],
  ['attention pay','Please pay attention to the teacher.','请注意听老师讲课。'],
  ['rule','This rule is easy to remember.','这条规则很容易记住。'],
  ['following','Read the following words.','读一读下面的单词。'],
  ['group','Our group has four students.','我们小组有四名学生。'],
  ['centre','The book is in the centre of the table.','书在桌子的中央。'],
  ['bold','My name is in bold.','我的名字是用粗体写的。'],
  ['person','She is a nice person.','她是一个很好的人。'],
  ['usually','I usually walk to school.','我通常步行上学。'],
  ['building','That is our classroom building.','那是我们的教学楼。'],
  ['mum','My mum is a teacher.','我的妈妈是一位老师。'],
  ['only','I have only one pencil.','我只有一支铅笔。'],
  ['every','I read every day.','我每天都阅读。'],
  ['go goes','Simon goes to school by bike.','西蒙骑自行车上学。'],
  ['welcome','Welcome to our school!','欢迎来到我们学校！'],
  ['about','Tell me about your school.','跟我说说你的学校吧。'],
  ['each other','We help each other.','我们互相帮助。'],
  ['according','Put the words into groups according to their sounds.','根据发音给单词分组。'],
  ['again','Please read the word again.','请再读一遍这个单词。'],
  ['based','This story is based on my school life.','这个故事是根据我的学校生活写的。'],
  ['circle','Circle the correct word.','圈出正确的单词。'],
  ['come','Come and meet my friend.','来认识一下我的朋友吧。'],
  ['far','My school is not far from home.','我的学校离家不远。'],
  ['game','This game is fun.','这个游戏很有趣。'],
  ['if','Ask me if you need help.','如果你需要帮助，就来问我。'],
  ['into','Put the book into your bag.','把书放进你的包里。'],
  ['meeting','We have a class meeting today.','我们今天开班会。'],
  ['need','I need a pen.','我需要一支钢笔。'],
  ['own','This is my own book.','这是我自己的书。'],
  ['part','Read the first part of the story.','读一读故事的第一部分。'],
  ['phrases','We learn new phrases in class.','我们在课堂上学习新短语。'],
  ['pictures','I like the pictures in this book.','我喜欢这本书里的图片。'],
  ['showing','Millie is showing me her photo.','米莉正在给我看她的照片。'],
  ['talk talking','We are talking about our hobbies.','我们正在谈论我们的爱好。'],
  ['try','Try to read this word.','试着读一读这个单词。'],
  ['unit','This unit is about new friends.','这一单元讲的是新朋友。'],
  ['way','This is a good way to learn.','这是一个学习的好方法。'],
  ['writing','I enjoy writing stories.','我喜欢写故事。'],
  ['a an','I have a book and an apple.','我有一本书和一个苹果。'],
  ['all','My classmates are all friendly.','我的同学们都很友好。'],
  ['also','I also like music.','我也喜欢音乐。'],
  ['am i’m','I am twelve. I’m a student.','我十二岁。我是一名学生。'],
  ['and','I like English and Maths.','我喜欢英语和数学。'],
  ['any','Do you have any hobbies?','你有什么爱好吗？'],
  ['are we’re','We are friends. We’re in the same class.','我们是朋友。我们在同一个班。'],
  ['aren’t','They aren’t in our class.','他们不在我们班。'],
  ['as','Use my picture as a model.','以我的图片作为范例。'],
  ['at','I am at school now.','我现在在学校。'],
  ['be','I want to be your friend.','我想成为你的朋友。'],
  ['before','I read before bed.','我睡觉前阅读。'],
  ['both','We both like reading.','我们俩都喜欢阅读。'],
  ['but','It is hard, but I like it.','这很难，但我喜欢。'],
  ['by','I go to school by bus.','我乘公共汽车上学。'],
  ['can','I can read this book.','我能读这本书。'],
  ['do','Do you like music?','你喜欢音乐吗？'],
  ['does','Does she like music?','她喜欢音乐吗？'],
  ['don’t','I don’t like this game.','我不喜欢这个游戏。'],
  ['for','This book is for you.','这本书是给你的。'],
  ['from','I am from China.','我来自中国。'],
  ['has','She has a new book.','她有一本新书。'],
  ['have','I have two good friends.','我有两个好朋友。'],
  ['he’s','He’s my new classmate.','他是我的新同学。'],
  ['here','Here is my new book.','这是我的新书。'],
  ['how','How old are you?','你多大了？'],
  ['is','She is my friend.','她是我的朋友。'],
  ['isn’t','This isn’t my book.','这不是我的书。'],
  ['it’s','It’s a nice school.','这是一所好学校。'],
  ['let’s','Let’s read together.','让我们一起阅读吧。'],
  ['many','I have many new friends.','我有许多新朋友。'],
  ['more','I want to learn more about you.','我想更多地了解你。'],
  ['much','I like my school very much.','我非常喜欢我的学校。'],
  ['not','I am not tall.','我个子不高。'],
  ['now','We are friends now.','我们现在是朋友了。'],
  ['oh','Oh, this is your book!','哦，这是你的书！'],
  ['ok','OK, let’s go to school.','好，让我们去上学吧。'],
  ['or','Do you like red or blue?','你喜欢红色还是蓝色？'],
  ['out','Look out of the window.','看窗外。'],
  ['over','My friend is over there.','我的朋友在那边。'],
  ['she’s','She’s good at music.','她擅长音乐。'],
  ['some','I have some new books.','我有一些新书。'],
  ['the','The girl is my friend.','那个女孩是我的朋友。'],
  ['then','Read the word, then write it.','先读这个单词，再把它写下来。'],
  ['there','There is a book on the desk.','书桌上有一本书。'],
  ['these','These are my new books.','这些是我的新书。'],
  ['they’re','They’re my classmates.','他们是我的同学。'],
  ['thing','What is this thing?','这个东西是什么？'],
  ['this','This is my classroom.','这是我的教室。'],
  ['those','Those are my friends.','那些人是我的朋友。'],
  ['too','I like reading too.','我也喜欢阅读。'],
  ['very','I am very happy today.','我今天非常高兴。'],
  ['what what’s','What’s your name?','你叫什么名字？'],
  ['when','When do you read?','你什么时候阅读？'],
  ['which','Which class are you in?','你在哪个班？'],
  ['with','I play with my friends.','我和朋友们一起玩。'],
  ['wow','Wow, your school is big!','哇，你的学校真大！'],
  ['you’re','You’re my best friend.','你是我最好的朋友。'],
  ['you’ve','You’ve got a nice book.','你有一本好看的书。'],
  ["daniel's",'This is Daniel’s book.','这是丹尼尔的书。'],
  ["millie's",'Millie’s hair is short.','米莉的头发很短。'],
  ['b c d e f o s t u','We learn the letters of the alphabet.','我们学习字母表中的字母。'],
  ['ju','The word use starts with the sound /juː/.','单词 use 以 /juː/ 这个音开头。']
];
